name: Deploy Public Folder to Pages

on:
  push:
    branches: [ "main" ] # Đổi thành "master" nếu repo của bạn dùng master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # Mã SHA chuẩn của actions/checkout@v4
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 

      - name: Setup Pages
        # Mã SHA chuẩn của actions/configure-pages@v5
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b 

      - name: Upload artifact
        # Mã SHA chuẩn của actions/upload-pages-artifact@v3
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dee4966286e9 
        with:
          # Ép GitHub Pages chỉ lấy các file trong thư mục public của bạn
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        # Mã SHA chuẩn của actions/deploy-pages@v4
        uses: actions/deploy-pages@d6db90164ad5ed86f2b6a8737221803cf87cf287 
